CREATE DATABASE tugas3

CREATE TABLE pembeli(
	id_pembeli VARCHAR(20) NOT NULL,
	nama_pembeli VARCHAR(30) NOT NULL,
	telepon VARCHAR(15) NOT NULL,
	alamat VARCHAR(100) NOT NULL,
	PRIMARY KEY(id_pembeli)
)ENGINE=MYISAM;

SHOW TABLES();